### ISSUE TITLE
(German) language setting inocuous

### ISSUE THREAD

**Issue by aroldo-sl** [myint/rst2beamer#3]
Hi there,

thanks a lot for rstbeamer3k. It is a great tool, specially for its compatibility with rst2htm and rst2latex.

But the the local ./docutils.conf entry

[general]
language=de

doesn't have the effect of translating, e.g. 'warnigs' to the German 'Warnung' through rst2beamer. The same with hint,tip, etc.

But when translanting exactly the same input.rst source file to output.html with rst2html the languang=de setting in ./docutils.conf is effective. And translanting the same input.rst source to output.tex with rst2latex also produces a correctly translated LateX and PDF via the same ./docutils.conf. This difference  gives me the impression  that the Beamer writer forgets the language setting that the Latex writer parses from ./docutils.conf. 

I'm using docutils 0.12, rst2beamer3k 0.8.4, Windows 8.

Thanks.

aroldo.

**Comment by myint** [comment]
I'm not familiar with the `docutils.conf`. But if anyone wants to send a relevant pull request, I'm willing to consider merging it.

**Comment by aroldo-sl** [comment]
Hi Steven, hi all,

thanks for looking at this.

The inocuousness of the 'language' option doesn't depend on docutils.conf.  Without a local ./docutils.conf, the call

$ rst2latex --input-encoding=utf-8 --language=de input.rst output.tex

translates "Warning" to "Warnung", but

$rst2beamer --input-encoding=utf-8 --language=de input.rst output.tex

leaves "Warning", "Note", etc in the original English version.

So it doesn't depend on whether I'm using a custom docutils.conf or not, because the command parameters overwrite the docutil.conf parameters anyway, as I'm told.

I'm not a programmer, but I intend to take a look at the Beamer writer source code in the course of the next days, perhaps I see something related there.

Thanks anyway for your attention.

Regards,

Aroldo.


unsing Python 3.4.2, Windows 8, docutils 0.12, rst2beamer3k 0.8.4

**Comment by myint** [comment]
I see. Could you provide complete input/output examples. I didn't know that the tools did any sort of translating.

**Comment by myint** [comment]
@aroldo-sl, please try out the [latest version in the master branch](https://github.com/myint/rst2beamer/commit/877da961ce3fc52b31ecbdbc3015a91b1dd2adb1). Let me know if it works.

Thanks
