### ISSUE TITLE
Didn't get the right result when trying the example "sections.rst"

### ISSUE THREAD

**Issue by gm6** [myint/rst2beamer#4]
Hi,
I'm trying using rst2beamer3k, but the example "sections.rst" doesn't give the right result.
In addition, When I use Generic Admonition:

.. admonition:: my own title

The result is "Admonition-my-own-title", while it should be "my own title". Seems it renders < admonition classes="admonition-my-own-title" >, not

< title >
 my own title

Thanks!

**Comment by myint** [comment]
Could you point me to `sections.rst`? Is this something in this repository?

**Comment by myint** [comment]
Seems to work for me. What version of rst2beamer3k are you using?

```rst
=====================
 Test of Admonitions
=====================

:Author: Test


Slide 1
=======

.. admonition:: my own title

    test
```

![screen shot 2015-08-07 at 10 42 15](https://cloud.githubusercontent.com/assets/1235108/9141905/03abcf4e-3cf1-11e5-81dd-845d2635ade0.png)

**Comment by gm6** [comment]
Hi,
Thank you for the reply! But the top of the slide should look like this:
https://www.dropbox.com/s/zp22hqvfmy5x54e/1.png?dl=0
And the bottom should be like this:
https://www.dropbox.com/s/697wrhoheafis5y/2.png?dl=0
I installed your package by pip install git+https, so it is the newest version.
rst2beamer doesn't work on generic admonition, but seems rst2beamer3k seems work.

**Comment by myint** [comment]
I see. I think you are looking for a different theme. Try `--theme=Warsaw`. That is the one that the original rst2beamer uses. The default theme in rst2beamer3k is Ilmenau.
