### ISSUE TITLE
Bug: Auto language detection does not work

### ISSUE THREAD

**Issue by bilderbuchi** [myint/rst2beamer#7]
I just noticed that if I use plain `code-block` directives without specifying the language, I don't get my python code snippets highlighted. When the language is supplied, this works as expected.
See the attached rendering of the `codeblocks.rst` - I have just removed `python` from the code-block of the directive, and get plain output. Supplying `rst2beamer --codeblocks-default-language=python codeblocks.rst codeblocks.tex` does not have an impact. 
Notice also how slide 5 does not get highlighting, and compare to the file [in the repo](https://github.com/myint/rst2beamer/blob/56bcf3cea2cd8d7c597df48ee55f43bcae55aa87/docs/examples/codeblocks.pdf).

Btw, my font is different from what's in the repo, but I guess that is down to the vagaries of latex?

This is on current master, Python 3.5.3, pygments 2.2.0, docutils 0.13.1, Ubuntu 16.04.

[codeblocks_no_guess_python.pdf](https://github.com/myint/rst2beamer/files/1191688/codeblocks_no_guess_python.pdf)

**Comment by myint** [comment]
I've fixed the `--codeblocks-default-language` bug.

Regarding language detection, I notice that Pygments won't detect code segments that are too short:

```rst
test
====

.. code-block::

    def foo():
        pass
```

But longer segments are detected:

```rst
test
====

.. code-block::

    class Foo():
        def __init__(self):
            pass

    def foo():
        pass
```

**Comment by bilderbuchi** [comment]
Ah, that's interesting. Maybe it does not have enough code to 100% detect the language? Btw, interestingly, when using sphinx it complains if no language is passed to the code-block directive...
